# Generated by Django 4.1.3 on 2022-11-17 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('storage', models.CharField(choices=[('lost', 'Потерял'), ('find', 'Нашел')], max_length=20)),
                ('title', models.CharField(max_length=200, verbose_name='Что вы нашли?')),
                ('slug', models.SlugField(blank=True, max_length=8, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='images')),
                ('status', models.CharField(choices=[('treatment', 'В обработке'), ('open', 'Открыто'), ('closed', 'Закрыто')], default='treatment', max_length=15)),
                ('text', models.TextField()),
                ('category', models.CharField(choices=[('documents', 'Документ'), ('keys', 'Ключи'), ('technique', 'Техника'), ('wallets', 'Кошельки'), ('animals', 'Животные'), ('decorations', 'Украшения'), ('bags', 'Сумки'), ('other', 'Другое')], max_length=100)),
                ('address', models.CharField(choices=[('XXXXXX', 'xxxxxx'), ('YYYYYY', 'yyyyyy')], max_length=100)),
                ('whatsapp', models.CharField(max_length=13)),
                ('telegram', models.CharField(max_length=100)),
                ('date', models.DateField(verbose_name='Дата находки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
