# Generated by Django 4.1.3 on 2022-11-24 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_remove_post_status_post_blur_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('treatment', 'В обработке'), ('open', 'Открыто'), ('closed', 'Закрыто')], default='treatment', max_length=15),
        ),
    ]
