# Generated by Django 4.1.3 on 2022-11-24 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blur_image',
            field=models.ImageField(upload_to='blur_images'),
        ),
    ]
