# Generated by Django 4.1.3 on 2022-11-26 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_alter_post_blur_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='blur_image',
        ),
    ]
