# Generated by Django 4.1.3 on 2022-11-26 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_remove_post_blur_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blur_image',
            field=models.ImageField(blank=True, upload_to='blur_image', verbose_name='blur_image'),
        ),
    ]
