# Generated by Django 4.1.3 on 2022-11-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0016_alter_post_blur_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blur_image',
            field=models.ImageField(blank=True, upload_to='blur_images'),
        ),
    ]
