# Generated by Django 4.1.3 on 2022-12-05 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0021_alter_post_blur_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reward',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
